spring:
  application:
    name: my-todo
  sql:
    init:
      platform: h2
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:my-todo;MODE=MYSQL"
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 1000
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

